INSERT INTO product VALUES(1, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(2, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(3, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(4, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(5, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(6, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(7, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(8, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(9, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(10, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(11, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(12, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(13, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(14, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(15, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(16, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(17, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(18, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(19, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(20, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(21, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(22, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(23, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(24, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(25, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(26, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(27, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(28, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(29, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(30, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(31, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(32, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(33, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(34, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(35, "pants","mantop","testimage5.jpg","kakaka",8000);
INSERT INTO product VALUES(36, "top","mantop" ,"testimage.jpg","man top",1000);
insert into product values(37, "pants","manbottom","testimage2.jpg","dog",5000);
insert into product values(38, "pants","mantop","testimage3.jpg","pororo",6000);
insert into product values(39, "pants","manbottom","testimage4.jpg","hahah",7000);
insert into product values(40, "pants","mantop","testimage5.jpg","kakaka",8000);

